/**
 * Content for the Falah Academy platform case study (/falah-platform).
 * A zero-budget school website + family-operations platform built and
 * operated by one person on free-tier infrastructure. Every number here
 * was measured from the codebase.
 */

export type ArchitectureBlock = {
  id: string;
  title: string;
  points: readonly string[];
};

export type EngineeringDecision = {
  decision: string;
  why: string;
  tradeoff: string;
};

export type ProblemRow = {
  who: string;
  what: string;
};

export type Outcome = {
  stat: string;
  label: string;
};

export type Screen = {
  src: string;
  alt: string;
  caption: string;
  width: number;
  height: number;
};

export const falahPlatformCaseStudy = {
  slug: "falah-platform",
  name: "Falah Academy — Website & Family Operations Platform",
  badge: "Live" as const,
  kicker: "Project case study",
  role: "Founder / President — sole architect, developer & operator",
  timeline: "June 2026 – present",
  live: "https://falahacademywa.org",
  portalNote: "portal at /platform/",
  metaDescription:
    "Case study: a zero-budget, production-grade website and family-operations platform for a new nonprofit Islamic school — public site, parent portal, admissions, attendance and fees on free-tier infrastructure, built and run by one person.",
  tagline:
    "A zero-budget, production-grade school platform for a new nonprofit Islamic school — public website, parent portal, admissions pipeline, attendance, fees and teacher workflows — built and operated by one person on free-tier infrastructure.",

  context:
    "Falah Academy is Kent, Washington's first full-time Islamic school (Pre-K–Grade 1 in year two, growing one grade per year). Like most new nonprofit schools it opened with a strong mission and no operating budget for software: no SIS, no parent app, no bookkeeping integration — tuition arrived by Zelle, attendance lived on paper, and parent communication was WhatsApp. I was the school's founder and President, and also the only person available to build its systems. The constraint that shaped every decision: the platform had to cost $0 to run, be operable by non-technical staff, and be maintainable by one part-time person indefinitely.",

  problem: {
    intro: "Three groups, three failure modes:",
    rows: [
      {
        who: "Parents",
        what: "No single place to see attendance, homework, Qur'an progress or fees; login letters and passwords by hand; “did my payment go through?” phone calls.",
      },
      {
        who: "Teachers",
        what: "Attendance and class notes on paper or in ad-hoc chats; no consistent way to reach one family vs the whole class; onboarding a teacher meant sharing five things by hand.",
      },
      {
        who: "Admin (me)",
        what: "Applications arriving as emails; students, fees and payments in a spreadsheet that drifted from the bank; every new student needed the same six documents regenerated by hand.",
      },
    ] as readonly ProblemRow[],
    closing:
      "Commercial school platforms start around $3–5 per student per month plus setup — real money for a 20-student school — and every one of them assumes an IT admin exists.",
  },

  solution: {
    intro:
      "Two front doors, one backend, and a deliberate rule about where each kind of user does their work.",
    callout:
      "The key design decision: teachers never log in to the portal. They work in Google Sheets, Forms and Drive — tools they already use on their phones — and Apps Script moves the data into Postgres. This removed an entire role, login flow, permission model and training burden, and it is why a school with no IT staff can run the system.",
    caption:
      "Two front doors (the static public site and the React family portal) and the teachers' Google tools all feed one Supabase backend, with three side systems and a dev → prod promotion path.",
  },

  architecture: [
    {
      id: "public-website",
      title: "Public website",
      points: [
        "Static HTML/CSS/JS on GitHub Pages with a custom domain and enforced HTTPS — no build step, no framework: fast, free, and editable by anyone.",
        "Admissions intake: a multi-step popup form uploads birth-certificate and immunization records to Google Drive via an Apps Script web app, emails the school via EmailJS, and creates an applicants row directly in Postgres through PostgREST using the publishable key and an insert-only RLS policy — so every application appears in the admin portal with zero manual entry.",
        "SEO / local: JSON-LD (School, BreadcrumbList, EducationalOccupationalProgram), a sitemap with lastmod, Google Business Profile, and Umami analytics. Ranks #1 organically for the brand and for “Islamic school Kent WA”.",
        "Programs section redesigned as a landing page plus four program pages and a partners page with a sticky sub-nav — built and reviewed locally first, then dev → prod.",
      ],
    },
    {
      id: "family-portal",
      title: "Family Portal (React SPA)",
      points: [
        "React 19 + TypeScript + Vite + Tailwind 4, with HashRouter so it deploys as static files under /platform/ on the same Pages site: ~4,900 lines of TypeScript across 18 admin screens and one parent home.",
        "Two roles only — admin and parent — enforced in the database, not the UI: a parent's session can only read the rows RLS allows, and the SPA has no privileged code path.",
        "Parent home: child switcher, attendance calendar, class-updates feed with photos, homework with due dates, Qur'an-progress timeline, fee status with “how to pay”, announcements with acknowledgement, in-app notifications, family-information self-service, and feedback.",
        "Admin: dashboard; students (roster, profile with photo approval, guardians, emergency, medical, documents); admissions (application detail, sibling detection, accept → enroll); parents; teachers; fees (plans, payments with edit/delete + audit); academics / Qur'an progress; assignments; class updates; calendar; announcements; feedback; reports (CSV); settings.",
      ],
    },
    {
      id: "data-layer",
      title: "Data layer (Supabase / Postgres)",
      points: [
        "29 tables, all with Row-Level Security; 76 policies, 21 functions / RPCs and 11 triggers. Helper predicates — is_admin(), is_my_child(), has_child_in_grade() — keep the policies readable and consistent.",
        "Schema evolved in 13 idempotent migration files (platform_schema.sql → phase13.sql), each safe to re-run, applied by hand to dev then prod — a deliberate choice over a migration tool for a one-person team.",
        "Business rules live in the database: accept_applicant() converts an application into student + enrollment atomically; column-protection triggers stop a parent changing their role, email, a child's DOB or guardian identity; notification triggers fire on payments, Qur'an comments, 3 consecutive absences, announcements and assignments; a payments_audit trigger records every payment edit or delete to audit_log.",
        "Storage: a public bucket for student photos (UUID paths, admin approval before display) and a private bucket for documents with signed URLs.",
        "Auth: email + password with a forced password change on first login; magic-link and reset emails through custom SMTP (Brevo) with proper redirect URLs.",
      ],
    },
    {
      id: "integration-layer",
      title: "Integration layer (Google Apps Script)",
      points: [
        "Three small scripts turn Google's free tools into the teacher interface.",
        "attendance-sync.gs — teachers mark today's attendance in a Sheet (one tab per grade, dropdowns); an on-change trigger upserts to Postgres and a nightly trigger clears the sheet. Teacher access to the sheet is reconciled hourly from the portal's Teachers table — add or deactivate a teacher in the portal and their access follows automatically.",
        "class-updates-form.gs — two Google Forms (a Class Update with four subject fields; a Qur'an Update with whole-class-or-one-student targeting). One submission fans out into per-subject rows in the portal; photos upload to Drive and are linked. The submitter allowlist is the same active-teacher list.",
        "drive-assignments-sync.gs — an hourly sync of per-grade Drive folders into assignments with due dates.",
      ],
    },
    {
      id: "automation",
      title: "Automation (GitHub Actions)",
      points: [
        "Daily notifications: a cron workflow calls a Postgres function that computes what each family needs to hear (fees due, absences, new updates) and sends digests via Brevo — the database decides, the workflow only delivers.",
        "Keep-alive: a twice-weekly ping so the free-tier database never pauses.",
        "Backups: a weekly encrypted pg_dump into a private repository. (Two GitHub Actions workflows in all.)",
      ],
    },
    {
      id: "environments",
      title: "Environments and delivery",
      points: [
        "Two full environments: a dev repo + dev Supabase project + dev site (/falahacademywa-dev/), and prod. Same code — only keys, a test banner and the bundle hash differ. Every change goes local preview → dev → prod, with a diff script that proves the two repos match.",
        "The bundle is built locally (vite build) and committed — no CI build server, no secrets in the pipeline.",
      ],
    },
  ] as readonly ArchitectureBlock[],

  decisions: [
    {
      decision: "Teachers use Google tools, not the portal",
      why: "Zero training, zero extra logins, works on any phone; removes a whole role from the auth model.",
      tradeoff: "Apps Script is a second codebase with its own deploy step.",
    },
    {
      decision: "Security in RLS, not in the app",
      why: "A static SPA can't hold secrets; the database is the only trustworthy boundary.",
      tradeoff:
        "76 policies to reason about; every new table needs its policy set.",
    },
    {
      decision: "Idempotent SQL files instead of a migration tool",
      why: "One person, two environments, no CI — re-runnable scripts are simpler and safer than tooling.",
      tradeoff: "Manual “run in dev, then prod” discipline.",
    },
    {
      decision: "Static hosting for both site and SPA",
      why: "$0, global CDN, HTTPS included, nothing to patch.",
      tradeoff: "HashRouter URLs; no server-side rendering.",
    },
    {
      decision: "Notifications computed in Postgres, delivered by a cron",
      why: "Logic next to the data, testable in SQL, provider-agnostic.",
      tradeoff: "Email provider limits (300/day on the free tier).",
    },
    {
      decision: "Audit trail on money edits",
      why: "Nonprofit books need “who changed what” without a full accounting system.",
      tradeoff: "An extra trigger + table growth (negligible at this scale).",
    },
  ] as readonly EngineeringDecision[],

  operations: {
    intro:
      "The platform is only half the job; running a school generates paperwork. Around the app I built small tools that turn one record into everything a family or teacher needs:",
    points: [
      "New-student package generator — from one admission record: a welcome letter on the school letterhead, a portal login letter with QR code, a grade supply list, a medical form, a media-consent form and an emergency-contact form → one print-ready PDF, filed into the student's records folder.",
      "Portal login letters generated in batch from a credentials sheet; a two-line SQL recipe for password resets.",
      "Scanner-style clean-up for photographed paper forms (OpenCV: page detection, perspective correction, shadow removal) so returned forms file as clean PDFs.",
      "A records system — a numbered OneDrive filing scheme mapped in a doc, so every document has one home.",
    ],
  },

  outcomes: [
    { stat: "$0", label: "per-month infrastructure" },
    { stat: "29", label: "Postgres tables" },
    { stat: "76", label: "RLS policies" },
    { stat: "109", label: "commits since June 2026" },
  ] as readonly Outcome[],

  results: [
    "$0/month infrastructure for the entire stack — Pages, the Supabase free tier, Google Workspace tools, the Brevo free tier and Actions minutes.",
    "Every family has a portal login; attendance, homework, class updates and fee status are visible the same day.",
    "Admissions: a website application becomes an admin-portal record with no re-typing; accept → enroll in one click; sibling detection across families.",
    "Teachers onboarded with three links; access provisioned automatically from the portal.",
    "Payments recorded with an audit trail and reconciled to QuickBooks.",
    "Search: #1 organic for the brand and for “Islamic school Kent WA”; Google Business Profile live in the local pack.",
    "Delivered incrementally over ~4 months alongside running the school, with 109 commits to the production repo.",
  ] as readonly string[],

  differently: [
    "Add a CI check (typecheck + lint + build on push, and a “committed bundle matches source” assertion). Skipped to keep the pipeline secret-free; cheap enough to add now.",
    "Rate-limit the public applicant insert (a captcha or an Edge Function) — an anonymous insert policy is convenient and slightly too open.",
    "Design the accept-flow around the school year from day one — the first version created a student without an enrollment for website applicants, a gap I fixed by hand twice before fixing the function.",
    "Bring the Apps Scripts under the same deploy discipline (clasp) instead of paste-into-editor.",
  ] as readonly string[],

  skills: [
    "Product ownership",
    "React / TypeScript",
    "Postgres schema design & RLS",
    "Supabase (Auth, Storage, Edge Functions)",
    "Integration design (Apps Script, PostgREST, Brevo, GitHub Actions)",
    "Static-site SEO & structured data",
    "Dev / prod environment discipline",
    "Document generation (Python / reportlab)",
    "Operating a system, not just building it",
  ] as readonly string[],

  stack: [
    "React",
    "TypeScript",
    "Vite",
    "Tailwind",
    "Supabase",
    "PostgreSQL",
    "Row-Level Security",
    "GitHub Pages",
    "GitHub Actions",
    "Google Apps Script",
    "Brevo",
  ] as readonly string[],

  screens: [
    {
      src: "/images/falah/parent-home.png",
      alt: "Family portal parent home (seeded development environment)",
      caption:
        "Parent home — child switcher, attendance calendar, class updates, homework, Qur'an progress and fee status.",
      width: 1600,
      height: 1000,
    },
    {
      src: "/images/falah/admin-students.png",
      alt: "Admin Students screen (seeded development environment)",
      caption:
        "Admin → Students — roster and profile with photo approval, guardians, emergency, medical and documents.",
      width: 1600,
      height: 1000,
    },
    {
      src: "/images/falah/admin-admissions.png",
      alt: "Admin Admissions screen showing the sibling badge (seeded development environment)",
      caption:
        "Admin → Admissions — application detail with sibling detection, and accept → enroll in one click.",
      width: 1600,
      height: 1000,
    },
    {
      src: "/images/falah/teacher-attendance-sheet.png",
      alt: "Teachers' attendance Google Sheet (seeded development environment)",
      caption:
        "Teachers' attendance Sheet — one tab per grade with dropdowns; an on-change trigger upserts to Postgres.",
      width: 1600,
      height: 1000,
    },
    {
      src: "/images/falah/programs-landing.png",
      alt: "Public website Programs landing page (seeded development environment)",
      caption:
        "Programs landing page — a landing page plus four program pages and a partners page with a sticky sub-nav.",
      width: 1600,
      height: 1000,
    },
  ] as readonly Screen[],
} as const;
